# Generated by Django 5.2.6 on 2025-09-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_facility_bus_facilities_order_trip_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='facilities',
            field=models.ManyToManyField(related_name='buses', to='station.facility'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=85, unique=True),
        ),
    ]
