# Generated by Django 5.2.6 on 2025-10-11 13:31

import station.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_alter_bus_facilities_alter_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='image',
            field=models.ImageField(null=True, upload_to=station.utils.create_bus_image_path),
        ),
    ]
